import type { AccordionGroup } from "../types/pokemon";

/**
 * Japanese syllabary groups for Pokemon organization
 */
export const ACCORDION_GROUPS: AccordionGroup[] = [
	{
		id: "a",
		name: "あ行",
		characters: ["あ", "い", "う", "え", "お"],
		isExpanded: false,
		activeCharacter: "あ",
	},
	{
		id: "ka",
		name: "か行",
		characters: ["か", "き", "く", "け", "こ"],
		isExpanded: false,
		activeCharacter: "か",
	},
	{
		id: "ga",
		name: "が行",
		characters: ["が", "ぎ", "ぐ", "げ", "ご"],
		isExpanded: false,
		activeCharacter: "が",
	},
	{
		id: "sa",
		name: "さ行",
		characters: ["さ", "し", "す", "せ", "そ"],
		isExpanded: false,
		activeCharacter: "さ",
	},
	{
		id: "za",
		name: "ざ行",
		characters: ["ざ", "じ", "ず", "ぜ", "ぞ"],
		isExpanded: false,
		activeCharacter: "ざ",
	},
	{
		id: "ta",
		name: "た行",
		characters: ["た", "ち", "つ", "て", "と"],
		isExpanded: false,
		activeCharacter: "た",
	},
	{
		id: "da",
		name: "だ行",
		characters: ["だ", "ぢ", "づ", "で", "ど"],
		isExpanded: false,
		activeCharacter: "だ",
	},
	{
		id: "na",
		name: "な行",
		characters: ["な", "に", "ぬ", "ね", "の"],
		isExpanded: false,
		activeCharacter: "な",
	},
	{
		id: "ha",
		name: "は行",
		characters: ["は", "ひ", "ふ", "へ", "ほ"],
		isExpanded: false,
		activeCharacter: "は",
	},
	{
		id: "ba",
		name: "ば行",
		characters: ["ば", "び", "ぶ", "べ", "ぼ"],
		isExpanded: false,
		activeCharacter: "ば",
	},
	{
		id: "pa",
		name: "ぱ行",
		characters: ["ぱ", "ぴ", "ぷ", "ぺ", "ぽ"],
		isExpanded: false,
		activeCharacter: "ぱ",
	},
	{
		id: "ma",
		name: "ま行",
		characters: ["ま", "み", "む", "め", "も"],
		isExpanded: false,
		activeCharacter: "ま",
	},
	{
		id: "ya",
		name: "や行",
		characters: ["や", "ゆ", "よ"],
		isExpanded: false,
		activeCharacter: "や",
	},
	{
		id: "ra",
		name: "ら行",
		characters: ["ら", "り", "る", "れ", "ろ"],
		isExpanded: false,
		activeCharacter: "ら",
	},
	{
		id: "wa",
		name: "わ行",
		characters: ["わ", "を", "ん"],
		isExpanded: false,
		activeCharacter: "わ",
	},
];

/**
 * Map hiragana to katakana characters for Pokemon lookup
 */
export const HIRAGANA_TO_KATAKANA: Record<string, string> = {
	あ: "ア",
	い: "イ",
	う: "ウ",
	え: "エ",
	お: "オ",
	か: "カ",
	き: "キ",
	く: "ク",
	け: "ケ",
	こ: "コ",
	が: "ガ",
	ぎ: "ギ",
	ぐ: "グ",
	げ: "ゲ",
	ご: "ゴ",
	さ: "サ",
	し: "シ",
	す: "ス",
	せ: "セ",
	そ: "ソ",
	ざ: "ザ",
	じ: "ジ",
	ず: "ズ",
	ぜ: "ゼ",
	ぞ: "ゾ",
	た: "タ",
	ち: "チ",
	つ: "ツ",
	て: "テ",
	と: "ト",
	だ: "ダ",
	ぢ: "ヂ",
	づ: "ヅ",
	で: "デ",
	ど: "ド",
	な: "ナ",
	に: "ニ",
	ぬ: "ヌ",
	ね: "ネ",
	の: "ノ",
	は: "ハ",
	ひ: "ヒ",
	ふ: "フ",
	へ: "ヘ",
	ほ: "ホ",
	ば: "バ",
	び: "ビ",
	ぶ: "ブ",
	べ: "ベ",
	ぼ: "ボ",
	ぱ: "パ",
	ぴ: "ピ",
	ぷ: "プ",
	ぺ: "ペ",
	ぽ: "ポ",
	ま: "マ",
	み: "ミ",
	む: "ム",
	め: "メ",
	も: "モ",
	や: "ヤ",
	ゆ: "ユ",
	よ: "ヨ",
	ら: "ラ",
	り: "リ",
	る: "ル",
	れ: "レ",
	ろ: "ロ",
	わ: "ワ",
	を: "ヲ",
	ん: "ン",
};
