// Initial Pokemon data for testing and development
export const initialPokemonData = [
  {
    name: "ピカチュウ",
    types: ["でんき"],
    generation: 1,
    classification: "ねずみポケモン",
    lastChar: "ウ",
  },
  {
    name: "フシギダネ",
    types: ["くさ", "どく"],
    generation: 1,
    classification: "たねポケモン",
    lastChar: "ネ",
  },
  {
    name: "ヒトカゲ",
    types: ["ほのお"],
    generation: 1,
    classification: "とかげポケモン",
    lastChar: "ゲ",
  },
  {
    name: "ゼニガメ",
    types: ["みず"],
    generation: 1,
    classification: "かめのこポケモン",
    lastChar: "メ",
  },
  {
    name: "ポッチャマ",
    types: ["みず"],
    generation: 4,
    classification: "ペンギンポケモン",
    lastChar: "マ",
  },
  {
    name: "イシツブテ",
    types: ["いわ", "じめん"],
    generation: 1,
    classification: "がんせきポケモン",
    lastChar: "テ",
  },
  {
    name: "ワニノコ",
    types: ["みず"],
    generation: 2,
    classification: "あごポケモン",
    lastChar: "コ",
  },
  {
    name: "ニャース",
    types: ["ノーマル"],
    generation: 1,
    classification: "ばけねこポケモン",
    lastChar: "ス",
  },
  {
    name: "サーナイト",
    types: ["エスパー", "フェアリー"],
    generation: 3,
    classification: "かんじょうポケモン",
    lastChar: "ト",
  },
  {
    name: "キリン",
    types: ["ノーマル"],
    generation: 5,
    classification: "きりんポケモン",
    lastChar: "ン",
  },
];
